apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
  labels:
    app: hello-job
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: hello-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: hello
        image: busybox:1.36
        command: ["/bin/sh", "-c", "echo Hello from Job; sleep 5"]
