apiVersion: v1
kind: Pod
metadata:
  name: myfirstcontainer
  labels:
    app.kubernetes.io/name: myfirstcontainer
spec:
  containers:
  - name: myfirstcontainer
    image: nginx:latest
    ports:
      - containerPort: 80
