apiVersion: v1
kind: Pod
metadata:
  name: resource
  labels:
    app.kubernetes.io/name: resource
spec:
  containers:
  - name: resource
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
    ports:
      - containerPort: 80
